In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
df = pd.read_csv("D:\CoEP\Smartbridge\Class_work\Churn_Modelling.csv")
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [3]:
df.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography          False
Gender             False
Age                False
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

In [4]:
x= df.iloc[:,3:13].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y= df.iloc[:,13].values
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer([("On",OneHotEncoder(),[1])], remainder="passthrough")
x = ct.fit_transform(x)
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [7]:
x.shape

(10000, 12)

In [8]:
x = x[:,1:]
x

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
x.shape

(10000, 11)

In [10]:
x[0]

array([0.0, 0.0, 619, 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
x[:,3] = lb.fit_transform(x[:,3])
x

array([[0.0, 0.0, 619, ..., 1, 1, 101348.88],
       [0.0, 1.0, 608, ..., 0, 1, 112542.58],
       [0.0, 0.0, 502, ..., 1, 0, 113931.57],
       ...,
       [0.0, 0.0, 709, ..., 0, 1, 42085.58],
       [1.0, 0.0, 772, ..., 1, 0, 92888.52],
       [0.0, 0.0, 792, ..., 1, 0, 38190.78]], dtype=object)

In [12]:
x[0]

array([0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88], dtype=object)

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test = train_test_split(x,y, test_size=0.3, random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

#The transformation aplied on x_train same we haev to apply pn x_test. if we do sc.fit_transform(x_test) here,
#then it will be some other transformation.
#execute this only onece nahitar next transformation will be applied to this transformed data.

In [15]:
x_train

array([[-0.56987189, -0.5731713 , -0.09792126, ...,  0.64198477,
         0.96683535, -0.76862426],
       [-0.56987189, -0.5731713 , -1.12612023, ...,  0.64198477,
        -1.03430227, -1.39359887],
       [-0.56987189, -0.5731713 , -0.62230274, ..., -1.55766936,
         0.96683535, -1.49739308],
       ...,
       [-0.56987189, -0.5731713 ,  0.89943174, ...,  0.64198477,
        -1.03430227,  1.41400417],
       [-0.56987189,  1.74467913, -0.62230274, ...,  0.64198477,
         0.96683535,  0.84625811],
       [ 1.75478035, -0.5731713 , -0.28299708, ...,  0.64198477,
        -1.03430227,  0.32689267]])

In [16]:
#save the transformation to apply in our model
from joblib import dump
dump(sc, "ANN_transform.save")

['ANN_transform.save']

## ANN layer building

In [17]:
import keras #for layers
from keras.models import Sequential #Sequential is used to initialise the model
from keras.layers import Dense # is used to build layers

Using TensorFlow backend.
C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

In [18]:
keras.__version__

'2.2.4'

In [19]:
model =  Sequential() #model is object of Sequential

In [20]:
x_train.shape #11 inputes are there

(7000, 11)

### Adding input layer

In [21]:
model.add(Dense(input_dim= 11, init="random_uniform",activation='relu',output_dim=15)) #input layer+ first hidden layer
'''
input_dim= 11 is the 11 input independent variables in dataset
init="random_uniform" randomly assigns weights
output contains positive values so apply relu activation function
output_dim=15 is the hidden layer neurons
single neuron is called perceptron
'''


C:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=11, activation="relu", units=15, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


'\ninput_dim= 11 is the 11 input independent variables in dataset\ninit="random_uniform" randomly assigns weights\noutput contains positive values so apply relu activation function\noutput_dim=15 is the hidden layer neurons\nsingle neuron is called perceptron\n'

In [22]:
model.add(Dense(output_dim=8,init="random_uniform",activation='relu')) 
#2nd hidden layer with 8 neurons
#1st hidden layer=15 neurons, 15//2=8 so 2nd layer with 8 neurons

C:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=8, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [23]:
model.add(Dense(output_dim=1,init="random_uniform",activation='sigmoid')) #output layer with 1 neuron

#activation='sigmoid' because output is 0 or 1

C:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


In [24]:
model.compile(optimizer="adam",loss= "binary_crossentropy",metrics=["accuracy"])

'''
adam is for batch gradient descent, SGD is for stochastic GD
take type of loss depend upon output variable like "categorical_crossentropy,binary_crossentropy"
cost function used is accuracy, for continuous values "mse" is used
'''



Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


'\nadam is for batch gradient descent, SGD is for stochastic GD\ntake type of loss depend upon output variable like "categorical_crossentropy,binary_crossentropy"\ncost function used is accuracy, for continuous values "mse" is used\n\n'

In [25]:
model.fit(x_train,y_train,epochs=50, batch_size=32)

#batch_size should be in powers of 2


Epoch 1/50
7000/7000 [==============================] - 1s 98us/step - loss: 0.5585 - acc: 0.7953
Epoch 2/50
7000/7000 [==============================] - 0s 51us/step - loss: 0.4331 - acc: 0.7977
Epoch 3/50
7000/7000 [==============================] - 0s 53us/step - loss: 0.4277 - acc: 0.7977
Epoch 4/50
7000/7000 [==============================] - 0s 69us/step - loss: 0.4233 - acc: 0.7977
Epoch 5/50
7000/7000 [==============================] - 0s 63us/step - loss: 0.4191 - acc: 0.8104
Epoch 6/50
7000/7000 [==============================] - 0s 58us/step - loss: 0.4155 - acc: 0.8274
Epoch 7/50
7000/7000 [==============================] - 0s 55us/step - loss: 0.4119 - acc: 0.8287
Epoch 8/50
7000/7000 [==============================] - 0s 58us/step - loss: 0.4089 - acc: 0.8324
Epoch 9/50
7000/7000 [==============================] - 0s 57us/step - loss: 0.4067 - acc: 0.8320
Epoch 10/50
7000/7000 [==============================] - 0s 55us/step - loss: 0.4050 - acc: 0.8333
Epoch 11/50
7000/7

In [26]:
y_pred= model.predict(x_test)
y_pred
#sigmoid range is between 0 to 1

array([[0.31077585],
       [0.39842978],
       [0.19140577],
       ...,
       [0.0765008 ],
       [0.02905142],
       [0.64222294]], dtype=float32)

In [27]:
y_pred= (y_pred>0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [28]:
y_test

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [29]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2229,  150],
       [ 303,  318]], dtype=int64)

In [30]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.849