### Step 1: Imporing libraries

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

### Step 2: Importing dataset

In [2]:
dataset = pd.read_csv("D:\CoEP\Smartbridge\Class_work\Data.csv")
dataset
#Purchased is the output here
#It is classification dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
type(dataset)

pandas.core.frame.DataFrame

In [4]:
dataset.describe() #describe works with only integer dataset

Age        Salary
count   9.000000      9.000000
mean   38.777778  63777.777778
std     7.693793  12265.579662
min    27.000000  48000.000000
25%    35.000000  54000.000000
50%    38.000000  61000.000000
75%    44.000000  72000.000000
max    50.000000  83000.000000

In [5]:
dataset.isnull().any()

Country      False
Age           True
Salary        True
Purchased    False
dtype: bool

In [6]:
dataset["Age"].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7    False
8    False
9    False
Name: Age, dtype: bool

In [7]:
dataset["Salary"].isnull()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8    False
9    False
Name: Salary, dtype: bool

### Step 3: Handling missing values

In [8]:
dataset["Age"].fillna((dataset["Age"].mean()), inplace= True)
dataset["Salary"].fillna((dataset["Salary"].mean()), inplace= True)

In [9]:
dataset.isnull().any()

Country      False
Age          False
Salary       False
Purchased    False
dtype: bool

In [10]:
dataset

Country        Age        Salary Purchased
0   France  44.000000  72000.000000        No
1    Spain  27.000000  48000.000000       Yes
2  Germany  30.000000  54000.000000        No
3    Spain  38.000000  61000.000000        No
4  Germany  40.000000  63777.777778       Yes
5   France  35.000000  58000.000000       Yes
6    Spain  38.777778  52000.000000        No
7   France  48.000000  79000.000000       Yes
8  Germany  50.000000  83000.000000        No
9   France  37.000000  67000.000000       Yes

In [11]:
dataset["Age"]= dataset["Age"].round()
dataset

Country   Age        Salary Purchased
0   France  44.0  72000.000000        No
1    Spain  27.0  48000.000000       Yes
2  Germany  30.0  54000.000000        No
3    Spain  38.0  61000.000000        No
4  Germany  40.0  63777.777778       Yes
5   France  35.0  58000.000000       Yes
6    Spain  39.0  52000.000000        No
7   France  48.0  79000.000000       Yes
8  Germany  50.0  83000.000000        No
9   France  37.0  67000.000000       Yes

In [12]:
dataset["Country"].value_counts()

France     4
Spain      3
Germany    3
Name: Country, dtype: int64

### Step 4: Separating dependent & independent variables

In [13]:
x= dataset.iloc[:,0:3].values
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 39.0, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [14]:
y= dataset.iloc[:,-1].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [15]:
x.shape

(10, 3)

In [16]:
x.ndim

2

In [17]:
y.ndim

1

### Step 5: Encoding categorical Text variables

In [18]:
import sklearn

In [19]:
sklearn.__version__

'0.22.1'

In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [22]:
ct = ColumnTransformer([("on", OneHotEncoder(),[0])], remainder ='passthrough')
x= ct.fit_transform(x)
x
#ColumnTransformer is applied on a particular column, values passed in list in form of tuple. Applied on 0th column.
#remainder ='passthrough' will retain other columns also which are not specified(other than 0th column)
#on is object of OneHotEncoder

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 39.0, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [24]:
x.shape

(10, 5)

### Removing dummy variables

In [25]:
x= x[:,1:]
x

array([[0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 30.0, 54000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 39.0, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [26]:
x.shape

(10, 4)

In [28]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
y= lb.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

### Step 6: Splitting train & test data

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2, random_state=0)

In [32]:
x_train

array([[1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 39.0, 52000.0],
       [0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [33]:
x_test

array([[1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [34]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [36]:
y_test

array([0, 0])